language: objective-c

env:
 global:
  - EnableNuGetPackageRestore=true 
 matrix:
  - MONO_VERSION="3.12.1"

before_install:
 - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
 - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

 
install:
  - mozroots --import --sync
 
script:
  - xbuild ./src/GeneticSharp.sln
  - nunit-console ./src/GeneticSharp.Domain.UnitTests/bin/Debug/GeneticSharp.Domain.UnitTests.dll ./src/GeneticSharp.Extensions.UnitTests/bin/Debug/GeneticSharp.Extensions.UnitTests.dll ./src/GeneticSharp.Infrastructure.Framework.UnitTests/bin/Debug/GeneticSharp.Infrastructure.Framework.UnitTests.dll ./src/GeneticSharp.Infrastructure.Threading.UnitTests/bin/Debug/GeneticSharp.Infrastructure.Threading.UnitTests.dll
